//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace splsys.web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Catalogo
    {
        public int IdCatalogoSec { get; set; }
        public string IdCatalogo { get; set; }
        public string IdTipoCatalogo { get; set; }
        public string Descripcion { get; set; }
        public string UsuarioCrea { get; set; }
        public Nullable<System.DateTime> FechaCrea { get; set; }
        public string UsuarioModifica { get; set; }
        public Nullable<System.DateTime> FechaModifica { get; set; }
    }
}
